services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: express_backend
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=/api
    command: npm run dev
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
